---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sophonte/portusforwarders.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/mkdir -p $DEPLOYPATH/css
    - /bin/mkdir -p $DEPLOYPATH/images
    - /bin/mkdir -p $DEPLOYPATH/js
    - /bin/cp -R assets/. $DEPLOYPATH/assets/
    - /bin/cp -R css/. $DEPLOYPATH/css/
    - /bin/cp -R images/. $DEPLOYPATH/images/
    - /bin/cp -R js/. $DEPLOYPATH/js/
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH