---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sophonte/portusforwarders.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/mkdir -p $DEPLOYPATH/css
    - /bin/mkdir -p $DEPLOYPATH/images
    - /bin/mkdir -p $DEPLOYPATH/js
    - /bin/cp -R portus-forwarders/assets/. $DEPLOYPATH/assets/
    - /bin/cp -R portus-forwarders/css/. $DEPLOYPATH/css/
    - /bin/cp -R portus-forwarders/images/. $DEPLOYPATH/images/
    - /bin/cp -R portus-forwarders/js/. $DEPLOYPATH/js/
    - /bin/cp portus-forwarders/about.html $DEPLOYPATH
    - /bin/cp portus-forwarders/contact.html $DEPLOYPATH
    - /bin/cp portus-forwarders/index.html $DEPLOYPATH
    - /bin/cp portus-forwarders/services.html $DEPLOYPATH
