deployment:
  tasks:
    - export DEPLOYPATH=/home/sophonte/portusforwarders.com/
    - mkdir -p $DEPLOYPATH
    - mkdir -p $DEPLOYPATH/assets
    - mkdir -p $DEPLOYPATH/css
    - mkdir -p $DEPLOYPATH/images
    - mkdir -p $DEPLOYPATH/js
    - cp -R assets/. $DEPLOYPATH/assets/
    - cp -R css/. $DEPLOYPATH/css/
    - cp -R images/. $DEPLOYPATH/images/
    - cp -R js/. $DEPLOYPATH/js/
    - cp -R *.html $DEPLOYPATH